go_import_path: github.com/larrabee/go-imagequant

language: go
go:
  - 1.9.x
  - tip

os:
  - linux
dist: trusty
sudo: required

matrix:
  allow_failures:
    - go: tip

gobuild_args: -v

# Install libimagequant from sources
install:
  - sudo apt-get install build-essential

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - go build ./...
